# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/learn/vivado/cod/lab5_5_Stage_CPU/lab5_5_Stage_CPU.srcs/sources_1/ip/instruction_mem_ip/instruction_mem_ip.xci
# IP: The module: 'instruction_mem_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/learn/vivado/cod/lab5_5_Stage_CPU/lab5_5_Stage_CPU.gen/sources_1/ip/instruction_mem_ip/instruction_mem_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instruction_mem_ip'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/learn/vivado/cod/lab5_5_Stage_CPU/lab5_5_Stage_CPU.srcs/sources_1/ip/instruction_mem_ip/instruction_mem_ip.xci
# IP: The module: 'instruction_mem_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/learn/vivado/cod/lab5_5_Stage_CPU/lab5_5_Stage_CPU.gen/sources_1/ip/instruction_mem_ip/instruction_mem_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instruction_mem_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
